# Generated by Django 5.1.6 on 2025-02-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todo",
            new_name="Todos",
        ),
    ]
