# Generated by Django 5.1.6 on 2025-02-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_rename_todo_todos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todos",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todos",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
