# Generated by Django 5.1.6 on 2025-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_todos_created_at_alter_todos_finished_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todos",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="data de criação"),
        ),
        migrations.AlterField(
            model_name="todos",
            name="deadline",
            field=models.DateField(verbose_name="data limite"),
        ),
        migrations.AlterField(
            model_name="todos",
            name="finished_at",
            field=models.DateField(null=True, verbose_name="data de finalização"),
        ),
        migrations.AlterField(
            model_name="todos",
            name="title",
            field=models.CharField(max_length=100, verbose_name="título"),
        ),
    ]
